on:
  workflow_call:
    outputs:
      new_version:
        description: 'The new version to release'
        value: ${{ jobs.semantic.outputs.new_release_version }}
      new_release_published:
        description: 'Whether a new release was published'
        value: ${{ jobs.semantic.outputs.new_release_published }}

name: Semantic Release

env:
  RUST_BACKTRACE: 1
  SEMREL_RUST_VERSION: 1.0.0-alpha.8


jobs:
    release:
        name: Semantic Release
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
            with:
                fetch-depth: 0
                persist-credentials: false

          - name: Install Python
            uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
            with:
              python-version: '3.10'

          - name: install commitizen
            run: pip install -U commitizen

          - name: Install Rust Stable
            uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.6
            with:
                profile: minimal
                toolchain: stable
                override: true

          # The release build is used in the Semantic Release step
          - name: Build
            uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b # v1.0.1
            with:
                command: build
                args: --release

          - name: Install Semantic Release Rust
            run: cargo install semantic-release-rust --version ${{ env.SEMREL_RUST_VERSION }}

          - name: Semantic Release
            uses: cycjimmy/semantic-release-action@91ab76a4a393a8d0c4739e9aea1818b56bc953ea # v3.4.0
            id: semantic
            with:
                semantic_version: 19
                extra_plugins: |
                    @semantic-release/exec@6
                    @semantic-release/git@10
            env:
                GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT_GITHUB }}
                CARGO_REGISTRY_TOKEN: ${{ secrets.SEMREL_CRATES_IO }}
