on:
  workflow_call:
    inputs:
      new_version:
        description: 'The new version to release'
        required: true
        type: string
      new_release_published:
        description: 'Whether a new release was published'
        required: true
        type: string

name: Upload Release Artifacts

env:
  RUST_BACKTRACE: 1

jobs:
    upload_binaries:
        name: Upload Binaries
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            include:
              - target: x86_64-pc-windows-gnu
                archive: zip
                platform: windows_x86_64
              - target: x86_64-unknown-linux-musl
                archive: tar.gz tar.bz2 tar.xz
                platform: linux_x86_64
              - target: x86_64-apple-darwin
                archive: zip
                platform: macos_x86_64
        steps:
          - name: Checkout
            uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
            with:
                fetch-depth: 0
                persist-credentials: false

          - name: Install Rust Stable
            uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.6
            with:
                profile: minimal
                toolchain: stable
                override: true

          - name: Create the event file
            run: |
              cat $GITHUB_EVENT_PATH | jq -r .release.tag_name | xargs -I {} echo 'RELEASE_VERSION="{}"' >> $GITHUB_ENV

          - name: Compile and release
            uses: rust-build/rust-build.action@7d5b0c135ddb825f7692d4d2d75e598184d15cec # v1.4.3
            env:
              GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT_GITHUB }}
            with:
              MINIFY: true
              RUSTTARGET: ${{ matrix.target }}
              ARCHIVE_TYPES: ${{ matrix.archive }}
              ARCHIVE_NAME: IPTMNet-CLI${{ env.RELEASE_VERSION }}${{matrix.platform}}
              EXTRA_FILES: "README.md LICENSE"
